# Generated by Django 4.0.4 on 2022-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
